### PR TITLE
fix so it works with `pull-ws`

### PR DESCRIPTION
**Pull request by ahdinosaur**
related to https://github.com/pull-stream/pull-stringify/pull/1.

have yet to get this actually working as expected with `pull-ws-server`, so work in progress.

BREAKING CHANGE
- use `pull-stringify@2`
- catch `JSON.parse` errors and send through stream
- skip parsing last value if empty string ''
- update README

### CODE REVIEW

**Comment by ahdinosaur** [comment]
this seems to be working with `pull-ws`, keen to merge this after https://github.com/pull-stream/pull-stringify/pull/1 (will need to update the `pull-stringify` version here to reflect the new version there).

**Comment by ahdinosaur** [comment]
updated deps to use `pull-stringify@2.0.0`, also added test case from https://github.com/diasdavid/pull-ndjson/issues/1

**Comment by dominictarr** [comment]
merged into 2.0.0

**Comment by ahdinosaur** [comment]
woot woot, thanks @dominictarr :smile:

**Pull request merged**
